services:
  - type: web
    name: check-in-system
    env: python
    region: frankfurt
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: FLASK_ENV
        value: production
    autoscaling:
      min: 1
      max: 1
    headers:
      - path: /*
        name: Cache-Control
        value: public, max-age=3600 